# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Study Sesh' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Study Sesh
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'JSQMessagesViewController'
  
  target 'Study SeshTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Study SeshUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
